### ISSUE TITLE
lost typing focus when adding node using Chinese input methods

### ISSUE THREAD

**Issue by huruka** [saqimtiaz/streams#2]
forgive my English is not very good.
Wiki about Chinese input method: https://en.wikipedia.org/wiki/Chinese_input_methods_for_computers
As the title says, when I click the "add node" button, start typing in the empty input box that appears, the **first keystroke** will invalidate the input method. I have to wait a few seconds and start typing again to input Chinese characters normally. 
Below is an animated picture, which may be more vivid.（I wanna input 测试(test), the first keystroke "c" failed）
![test](https://user-images.githubusercontent.com/5837707/87869840-91d39100-c9d5-11ea-8d69-1443142e7c38.gif)

**Comment by saqimtiaz** [comment]
@huruka thank you for the bug report. This is a known issue caused by the way one of the TiddlyWiki keyboard widgets work.

I have a modification of the widget that solves this problem, but it needs more testing before I can make a pull request for the core and release a plugin update to fix this issue.

The temporary solution is to always start each node with a space character " ".

**Comment by saqimtiaz** [comment]
[Fixed ](https://github.com/saqimtiaz/streams/commit/5b24b2327da4023ea73cf8ee204c09453a9d6f0e)
There will be an updated plugin available later today.
