### ISSUE TITLE
Feature request: stream-root-title as a field

### ISSUE THREAD

**Issue by kebifurai** [saqimtiaz/streams#5]
Currently `<<stream-root-title>>` doesn't work if it is run inside a node tiddler, so having a field `root-title` like `parent` could solve this problem.

**Comment by saqimtiaz** [comment]
@kebifurai any issues you are encountering with using `stream-root-title` inside a node tiddler have to do with the code you are using it in. This is a standard tiddlywiki variable with nothing special about it and can be used like any other variable in TW.

Your problems are likely due to the fact that your code runs inside an editor toolbar button, which have a different context than the body of a tiddler.

Furthermore, adding this as a field would not make any sense considering that the value of the variable depends on how the node is being displayed. That is, the same node tiddler can have different values for stream-root-title depending on which part of the stream is open in the story river.

In a Stream with nodes:
A
- B
- C
-- D

If we open the tiddler C, D will have a stream-root-title with value D. If you open tiddler A, the stream-root-title will be tiddler A.

I recommend trying to use targetTiddler and storyTiddler variables instead.
